FROM alpine:3.15
RUN apk add --no-cache\
	clang llvm compiler-rt compiler-rt-static lld make musl-dev clang-extra-tools\
	python3

COPY . /app/calculator
WORKDIR /app/calculator

ENV ADD_FLAGS "-fuse-ld=lld --rtlib=compiler-rt -D_CRT_SECURE_NO_WARNINGS"
RUN make FLAGS+=$(ADD_FLAGS) test
RUN make FLAGS+=$(ADD_FLAGS) integrationtest
